language: c
install: make
script: make
deploy:
  provider: releases
  api_key:
    secure: RPoR5UlS2Pp0wBieAufJR8WCLeolT6HqIC4m+BeXFL8ldgeWUo2KKh4Ns20ZmLRWces9YpWgYhmEHpszjs0jvjbAz5+4iDTegjozNXg6WGZk9NtSp86Hr7L4YjgIlL1MR2NLE/yMdOtm4yYRs0/uwlVYJJ1kfnleiJ6rf0ZXx2Omgf6ilfe52qhOAI1uRMg2MfORg879G0w+iV8wksS4sGdc6/ZCVRWJSt+oJXpzRY3b/jMzKR4TKlaGTibhBGUwzNLDMHozkd5uhLF+NIHVxP4pFAuLwP+obr7WaN9r8J2jueSuZT4u9tBQ9mUyk/JQWOIVxPUZcG4FxLTJyrynZ4ltueE0fthi+u92KRrUI2Pe47u9zcOCsrUD34L5xp4D33Bda2Wlj389a0p9jm8UbFYUyNXJVTN/oQKjj7ke0IODR1qz+KuK2F2jnNNhOkKpVDwf7Kgs1iPFJeiOlq5DEJkbjL+r2ssCHp4m67JPaO2nl56tjfIelpuumi8TC7m7qJcx2HbPk7vTze/u357VhTPHcui3Q7u2o2/vBb5jJPtxeKiipFYdakTI0GDdr1lLqwkMb6k9tko+GcAtCsRh/7HBmkh2ROKlUPAx3jny1sxpoeDLF3LA1vUAkCnwcxHvTzQlOZyLl1AFWoa/dm7LvMhRsUqhvG1BWBCM06pH0HU=
  file_glob: true
  file:
    - "openwrt/*.ipk"
  skip_cleanup: true
  on:
    tags: true
